name: Coding Standards

on:
  push:
  pull_request:

jobs:
  coding-standards:
    name: Check Coding Standards
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Composer require Symfony ${{ matrix.symfony }}
        run: SYMFONY_REQUIRE=${{ matrix.symfony }} composer update --no-interaction --no-progress --prefer-dist --verbose

      - name: Install php-cs-fixer
        run: cd tools/php-cs-fixer && composer install --no-interaction --no-progress --prefer-dist --verbose

      - name: Check PHP Coding Standards
        run: make php-cs-fixer-dry-run
